#!/bin/sh
#
# Random configure cpux frequency.

CPUDIR="/sys/devices/system/cpu"
CPUCORE="0 1 2 3 4 5 6 7"

while false
do
    echo "Hello World. Dynamic Configure Frequency"
    date
    sleep 60
    echo "performance" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
    cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq

    sleep 60
    echo "powersave" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
    cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
done
